version: '2'
services:
  db:
    image: postgres
    ports:
      - "5431:5431"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    command: -p 5431

volumes:
  pgdata: