version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username

volumes:
  pgdata: